blueprint: acquisitions

title: Markdown tables
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:

            content:
              unset@: true

            header.media_order:
              unset@: true

            header.sections:
              type: list
              style: vertical
              fields:
                .subtitle:
                  type: text
                  label: Titre
                .pictures:
                  type: file
                  label: Images des œuvres
                  accept:
                    - image/*
                  multiple: true
                  preview_images: true
                .content:
                  type: markdown
                  validate:
                    type: textarea