blueprint: table

title: Markdown tables
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:

            content:
              unset@: true

            header.media_order:
              unset@: true

            header.sections:
              type: list
              style: vertical
              fields:
                .content:
                  type: markdown
                  validate:
                    type: textarea
                .class_name:
                  type: selectize
                  label: Type de tableau
                  selectize:
                      options:
                          - text: "flag"
                            value: "flag"
                          - text: "sum-row"
                            value: "sum-row"
                          - text: "head-row"
                            value: "head-row"